# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
# config.ssh.insert_key = false
#  config.ssh.private_key_path = "insecure_private_key"
  
  config.vm.define "server", primary: true do |server|
	  server.vm.provider "virtualbox" do |vb|
	    vb.customize ["modifyvm", :id, "--nic3", "intnet"]
	    vb.customize ["modifyvm", :id, "--nic4", "intnet"]
	    vb.memory = "256"
	  end

    server.ssh.insert_key = false

    server.vm.hostname = "server"
    server.vm.box = "generic/alpine38"
    server.vm.network "public_network"
    server.vm.provision "file", source: "dhcpd.conf", destination: "/tmp/"
    server.vm.provision "file", source: "interfaces", destination: "/tmp/"
    server.vm.provision "shell", inline: <<-SHELL
#     sudo ip addr add 192.168.10.1/24 dev eth2
#     sudo ip link set eth2 up
#     sudo ip addr add 10.5.92.1/24 dev eth3
#     sudo ip link set eth3 up
      sudo cp /tmp/interfaces /etc/network/
      sudo rc-service networking restart
       echo "update apk"
       sudo apk update
       echo "install dhcp server"
       sudo apk add dhcp
       sudo cp /tmp/dhcpd.conf /etc/dhcp/
       sudo rc-update add dhcpd
       sudo rc-service dhcpd start
     SHELL
  end
  
  config.vm.define "client1" do |client1|
     client1.vm.provider "virtualbox" do |vb|
       vb.customize ["modifyvm", :id, "--nic3", "intnet"]
       vb.customize ["modifyvm", :id, "--nic4", "intnet"]
#      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
       vb.memory = "1024"
#      vb.customize ["modifyvm", :id, "--cableconnect1", "on"]
#      use_dhcp_assigned_default_route = false
     end
    client1.vm.hostname = "client1"
    client1.vm.box = "ubuntu/jammy64"
    client1.vm.provision "file", source: "01-network.yaml", destination: "/tmp/"
    client1.vm.provision "shell", inline: <<-SHELL
      sudo cp /tmp/01-network.yaml /etc/netplan/
      sudo echo "network: {config: disabled}" > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
      sudo cat /etc/netplan/50-cloud-init.yaml 
      sudo rm /etc/netplan/50-cloud-init.yaml 
      sudo ip link set enp0s9 up
      sudo ip link set enp0s10 up
      sudo apt -y install net-tools
      sudo netplan apply
    SHELL




#   client1.vm.network "private_network", ip: "192.168.10.2"
#    client1.vm.network "private_network", ip: "10.5.92.2",     
#      virtualbox__intnet: "vboxnet3", auto_config: false
#      use_dhcp_assigned_default_route = false
#    client1.vm.network "private_network", ip: "172.16.17.1"
#    client1.vm.provision "shell", inline: <<-SHELL
#     echo << EOF
#      auto eth1
#      iface eth1 inet dhcp
#      hostname client1
#     EOF
#
#      sudo route add 10.5.92.1 dev eth1
#      sudo /etc/init.d/networking restart
#      ip a
#    SHELL
#
#
#
#     echo "auto eth1\n
#     echo "iface eth1 inet dhcp" >> /etc/network/interfaces
#     echo "hostname client1" >> /etc/network/interfaces
#     sudo ip link set dev eth1 up
##    sudo ifconfig eth1 192.168.0.17 netmask 255.255.255.0 up
#     sudo route add 10.5.92.1 dev eth1
#     sudo udhcpc -i eth1 -r 10.5.92.1
#    SHELL
  end

  config.vm.define "client2" do |client2|
    client2.vm.hostname = "client2"
    client2.vm.box = "generic/alpine38"
    client2.vm.network "private_network", ip: "192.168.10.2",
      virtualbox__intnet: "test"
    client2.vm.network "private_network", ip: "172.16.17.2"
    client2.vm.provision "shell", inline: <<-SHELL
     echo "auto eth1" >> /etc/network/interfaces
     echo "iface eth1 inet dhcp" >> /etc/network/interfaces
     echo "hostname client2" >> /etc/network/interfaces
     sudo ip link set dev eth1 up
     sudo route add 192.168.10.1 dev eth1
     sudo udhcpc -i eth1 -r 192.168.10.1
    SHELL
  end

  config.vm.define "test1" do |test1|
  test1.vm.provider "virtualbox" do |vb|
#   vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.memory = "1024"
  end
    test1.vm.box = "ubuntu/jammy64"
#    test1.ssh.insert_key = false
  end
end

